// <auto-generated />
namespace Recruitment_Portal_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202301281417259_addedProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
